/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salon_premiun;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Carlos
 */
public class salon_premiun_nuevoEvento extends javax.swing.JDialog {

    /**
     * Creates new form salon_premiun_form
     */
    public salon_premiun_nuevoEvento() {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();

        //centramos el formulario para que aparezca en el centro
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        btGuardar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblNumpersonas = new javax.swing.JLabel();
        txtNumpersonas = new javax.swing.JTextField();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        lblTipococina = new javax.swing.JLabel();
        cbTipococina = new javax.swing.JComboBox<>();
        spcSeparador = new javax.swing.JSeparator();
        lblJornadas = new javax.swing.JLabel();
        txtNumjornadas = new javax.swing.JTextField();
        chkHabitacionesasistentes = new javax.swing.JCheckBox();
        cbTipo = new javax.swing.JComboBox<>();
        lblDatospersonales = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblTelf = new javax.swing.JLabel();
        txtTelf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDatospersonales1 = new javax.swing.JLabel();
        chkCapilla = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Evento");
        setResizable(false);

        btGuardar.setBackground(Color.BLUE);
        btGuardar.setText("Guardar");
        btGuardar.setToolTipText("Pulda para guaradar el evento");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblFecha.setText("Fecha del evento:");

        lblTipo.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblTipo.setText("Tipo:");

        lblNumpersonas.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblNumpersonas.setText("Nº de personas:");

        txtNumpersonas.setToolTipText("Selecciona el número de personas");

        dtcFecha.setToolTipText("Selecciona una fecha");

        lblTipococina.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblTipococina.setText("Tipo de cocina:");

        cbTipococina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bufé", "Wok", "Carta", "Cita Chef", "No precisa" }));
        cbTipococina.setToolTipText("Selecciona el tipo de cocina");

        lblJornadas.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblJornadas.setText("Nº de jornadas");
        lblJornadas.setEnabled(false);

        txtNumjornadas.setToolTipText("Número de jornadas del evento");
        txtNumjornadas.setEnabled(false);

        chkHabitacionesasistentes.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        chkHabitacionesasistentes.setText("¿Habitaciones para asistentes?");
        chkHabitacionesasistentes.setToolTipText("Marcar si los asistentes necesitan habitaciones");
        chkHabitacionesasistentes.setEnabled(false);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso", "Boda" }));
        cbTipo.setToolTipText("Selecciona el tipo de evento");
        cbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoItemStateChanged(evt);
            }
        });

        lblDatospersonales.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblDatospersonales.setText("Datos Personales:");

        lblNombre.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblNombre.setText("Nombre");

        lblApellidos.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblApellidos.setText("Apellidos");

        txtNombre.setToolTipText("Introduce tu nombre");

        txtApellidos.setToolTipText("Introduce tus apellidos");

        lblDNI.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblDNI.setText("DNI");

        txtDNI.setToolTipText("Introduce tu número de DNI");

        lblTelf.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblTelf.setText("Teléfono");

        txtTelf.setToolTipText("Introduce tu número de teléfono");

        lblDatospersonales1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        lblDatospersonales1.setText("Opciones:");

        chkCapilla.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        chkCapilla.setText("¿Capilla para la boda?");
        chkCapilla.setToolTipText("Marcar si los asistentes necesitan habitaciones");
        chkCapilla.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatospersonales1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumpersonas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtcFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(cbTipococina, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumpersonas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipococina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(chkCapilla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spcSeparador, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addGap(112, 112, 112)
                                        .addComponent(lblApellidos))
                                    .addComponent(lblDatospersonales)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNumjornadas, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblJornadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(32, 32, 32)
                                        .addComponent(chkHabitacionesasistentes))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDNI)
                                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelf)
                                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 33, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatospersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(lblTelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblNumpersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumpersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipococina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipococina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spcSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatospersonales1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJornadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumjornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHabitacionesasistentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(chkCapilla))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoItemStateChanged

        if (cbTipo.getSelectedItem().toString().equals("Congreso")) {

            this.lblJornadas.setEnabled(true);
            this.txtNumjornadas.setEnabled(true);
            this.chkHabitacionesasistentes.setEnabled(true);
            this.chkCapilla.setEnabled(false);

        } else if (cbTipo.getSelectedItem().toString().equals("Boda")) {

            this.lblJornadas.setEnabled(false);
            this.txtNumjornadas.setEnabled(false);
            this.chkHabitacionesasistentes.setEnabled(false);
            this.chkCapilla.setEnabled(true);

        } else {

            this.lblJornadas.setEnabled(false);
            this.txtNumjornadas.setEnabled(false);
            this.chkHabitacionesasistentes.setEnabled(false);
            this.chkCapilla.setEnabled(false);
        }


    }//GEN-LAST:event_cbTipoItemStateChanged

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        JOptionPane.showMessageDialog(rootPane, "Has registrado un nuevo evento de tipo \"" + this.cbTipo.getSelectedItem().toString() + "\", gracias."); 
    }//GEN-LAST:event_btGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbTipococina;
    private javax.swing.JCheckBox chkCapilla;
    private javax.swing.JCheckBox chkHabitacionesasistentes;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDatospersonales;
    private javax.swing.JLabel lblDatospersonales1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblJornadas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumpersonas;
    private javax.swing.JLabel lblTelf;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipococina;
    private javax.swing.JSeparator spcSeparador;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumjornadas;
    private javax.swing.JTextField txtNumpersonas;
    private javax.swing.JTextField txtTelf;
    // End of variables declaration//GEN-END:variables
}
