/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salon_premiun;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author Carlos
 */
public class salon_premiun_mainForm extends javax.swing.JFrame {

    /**
     * Creates new form salon_premiun_mainForm
     */
    public salon_premiun_mainForm() {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salon_premiun_nuevoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();

        //centramos el formulario para que aparezca en el centro
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNuevoEvento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mniEvento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salon Premiun");
        setResizable(false);

        btNuevoEvento.setBackground(Color.RED);
        btNuevoEvento.setText("Nuevo Evento");
        btNuevoEvento.setToolTipText("Pulsa para crear un nuevo evento");
        btNuevoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoEventoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salon_image.png"))); // NOI18N

        mnMenu.setText("Nuevo Evento");

        mniEvento.setText("Crear nuevo evento");
        mniEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEventoActionPerformed(evt);
            }
        });
        mnMenu.add(mniEvento);

        jMenuBar1.add(mnMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(btNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(btNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEventoActionPerformed

        //abrimos la interfaz en un hilo nuevo
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salon_premiun_nuevoEvento().setVisible(true);
            }
        });
    }//GEN-LAST:event_mniEventoActionPerformed

    
    
    private void btNuevoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoEventoActionPerformed
        //abrimos la interfaz en un hilo nuevo
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salon_premiun_nuevoEvento().setVisible(true);
            }
        });
    }//GEN-LAST:event_btNuevoEventoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNuevoEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenuItem mniEvento;
    // End of variables declaration//GEN-END:variables
}
